# Generated by Django 4.1.7 on 2023-03-05 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Категория поста', 'verbose_name_plural': 'категории постов'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='game_forum.PostCategory', to='game_forum.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
