# Generated by Django 4.1.7 on 2023-03-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_forum', '0002_alter_comment_options_alter_postcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
